version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - POSTGRES_PRISMA_URL=postgresql://postgres:postgres@postgres:5432/rylix?schema=public
      - POSTGRES_URL_NON_POOLING=postgresql://postgres:postgres@postgres:5432/rylix?schema=public
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=rylix
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-nextauth-secret
      # Add other environment variables here

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rylix
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

